version: '3.9'

services:
  air_quality_producer:
    container_name: air_quality_producer
    build: .
    networks:
      - server_air_quality_network

networks:
  server_air_quality_network:
    external: true