version: '3.9'

services:
  air_quality_server:
    container_name: air_quality_server
    build: .
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - air_quality_db
      - air_quality_redis
      - air_quality_rabbitmq
    networks:
      - air_quality_network

  air_quality_db:
    container_name: air_quality_db
    image: postgres:latest
    environment:
      - POSTGRES_DB=air_quality_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root1234
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - air_quality_network

  air_quality_rabbitmq:
    container_name: air_quality_rabbitmq
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root1234
    ports:
      - "5672:5672"
      - "15672:15672"  # Порт для управления через веб-интерфейс
    networks:
      - air_quality_network

  air_quality_redis:
    container_name: air_quality_redis
    image: redis:latest
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=root1234
    command: redis-server --appendonly yes --requirepass root1234
    networks:
      - air_quality_network
    volumes:
      - redis-data:/data

networks:
  air_quality_network:
    driver: bridge

volumes:
  db-data:
  redis-data: